### ISSUE TITLE
pip3 install json issues

### ISSUE THREAD

**Issue by Drifterino** [RhythmLunatic/discord2groupme#5]
Love the work you've done here. I'm no programmer but I know a bit. I've gotten through most of the steps but in node.js when putting in 'pip3 install json' I'm getting "Could not find a version that satisfies the requirement json (from versions: ) No matching distribution found for json?" as an asnwer. do I need to be in a certain folder for it to work?

Thanks

**Comment by RhythmLunatic** [comment]
It looks like the json library isn't in the pip repos any more. It might have been integrated into Python3.6.

**Comment by RhythmLunatic** [comment]
The commands have to be run in the folder where you downloaded the files in this repo. In other words, a folder containing only config.json, discordhook.js, and groupmehook.py.

**Comment by Drifterino** [comment]
I got a little further this time but having trouble getting the python part to work. It's having trouble getting my groupme user id, and it's not printing it out when I leave it blank. I've tried putting in my token and other things but it's saying it can't convert to int. Is the groupme_user_id supposed to be just number, if so what else can I try to find it? I've searched everywhere.

**Comment by Drifterino** [comment]
Is there a special permission I need to grant the program? It's running into a wall of some sorts. Entering zero prints this in the terminal.

"Traceback (most recent call last):
  File "groupmehook.py", line 98, in <module>
    run()
  File "groupmehook.py", line 88, in run
    httpd = server_class(server_address, handler_class)
  File "C:\Users\TheVa\AppData\Local\Programs\Python\Python36\lib\socketserver.py", line 453, in __init__
    self.server_bind()
  File "C:\Users\TheVa\AppData\Local\Programs\Python\Python36\lib\http\server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "C:\Users\TheVa\AppData\Local\Programs\Python\Python36\lib\socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions"

**Comment by RhythmLunatic** [comment]
You probably need to specify a port above 1000 as an argument

**Comment by Drifterino** [comment]
Worked like a charm!

python3 hasn't worked as a command for me, I've been using just 'python'

I did this and got:
C:\Users\TheVa\Documents\discord2groupme-master>python groupmehook.py 9999
HTTP server running on port 9999

from there it didn't post anything even when I messaged in the group chat

as of the node.js code it's been running as:
Bot has started, with 2 users, in 0 channels of 0 guilds.
(node:2228) DeprecationWarning: ClientUser#setGame: use ClientUser#setActivity instead

with no activity either. I feel like it's almost there, what am I missing?

Also thank you for your help so far.

**Comment by RhythmLunatic** [comment]
The callback URL at https://dev.groupme.com has to be the IP address and port of the server you're running the groupme hook from.

ex. `http://111.222.333:9999` for an IP address of 111.222.333 and a port of 9999.

If you're running this from your house, configuring port forwarding is outside the scope of the program and you should look up a guide, otherwise it should work fine.

**Comment by RhythmLunatic** [comment]
Last I checked, port forwarding with hamachi is just tunneling, but I haven't checked in years. You need to configure port forwarding on your router, set port 9999 from the outside to point towards port 9999 of the computer running the GroupMe hook.

You can use http://canyouseeme.org/ or similar to check if port 9999 is open on your router & computer. (While the GroupMe hook is running.)

If heroku gives you a dedicated IP address, then yes, you should use it. (Alternatively you can buy a Raspberry Pi or similar small Linux computer and leave it plugged in all day if you have working port forwarding, but you should pick whatever you want.)

**Comment by Drifterino** [comment]
That works out well then. I'll try the port forwarding and see if I can put it on my raspberry. Thanks for all your help!
